name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub registry NuGet source
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/dotnet-websharper/index.json \
            --name github \
            --username Csucsuy \
            --password "${{ secrets.FEED }}" \
            --store-password-in-clear-text

      - run: npm install -g vite
      - run: dotnet build
      - run: npx vite build --outDir ../../dist --base ./
        working-directory: bin/html
      # HTML fájlok másolása, ha léteznek
      - name: Copy additional HTML files to dist/
        run: |
          if [ -d "bin/html" ]; then
             cp -r bin/html/* dist/
          else
            echo "HTML files not found!"
            exit 1
          fi
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.FEED }}
          BRANCH: gh-pages
          FOLDER: dist