name: Deploy to GitHub Pages

# Mikor fusson a workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Jogosultságok a Pages deploy-hoz
permissions:
  contents: read
  pages: write
  id-token: write

# Konkurens futások kezelése
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klónozása
      - name: Checkout
        uses: actions/checkout@v4

      # 2. .NET környezet beállítása
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 3. Projekt fordítása
      - name: Build
        run: dotnet build --configuration Release

      # 4. Statikus fájlok feltöltése artifact-ként
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./wwwroot

      # 5. Deploy a GitHub Pages-re
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4